import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import twilio from 'twilio';

import { createTwilioRequestVerifier } from '../src/sms/twilioRequestVerifier.js';

// A fabricated token used only in tests — never a real Twilio credential.
const authToken = 'fake-test-auth-token-not-real';
// The "public" URL Twilio believes it's calling — deliberately different
// from wherever the test HTTP server actually listens, to prove signature
// validation is based on the configured public webhook URL, not whatever
// host/port the request physically arrived on (important once this app
// sits behind a tunnel/proxy).
const webhookBaseUrl = 'https://example.test';

function fakeRequest({ url = '/sms', signature } = {}) {
  return {
    url,
    headers: signature ? { 'x-twilio-signature': signature } : {},
  };
}

describe('createTwilioRequestVerifier', () => {
  it('requires an auth token', () => {
    assert.throws(() => createTwilioRequestVerifier({ webhookBaseUrl }));
  });

  it('requires a public webhook base URL', () => {
    assert.throws(() => createTwilioRequestVerifier({ authToken }));
  });

  it('accepts a request bearing a genuine signature (generated by the Twilio SDK itself, not our own crypto)', () => {
    const params = { Body: 'hello', From: '+15551234567' };
    const signature = twilio.getExpectedTwilioSignature(authToken, `${webhookBaseUrl}/sms`, params);
    const verify = createTwilioRequestVerifier({ authToken, webhookBaseUrl });

    const result = verify({ req: fakeRequest({ signature }), params });

    assert.equal(result, true);
  });

  it('rejects a request whose params were tampered with after signing (proves the full payload is covered)', () => {
    const signedParams = { Body: 'hello' };
    const signature = twilio.getExpectedTwilioSignature(authToken, `${webhookBaseUrl}/sms`, signedParams);
    const verify = createTwilioRequestVerifier({ authToken, webhookBaseUrl });

    const result = verify({ req: fakeRequest({ signature }), params: { Body: 'tampered' } });

    assert.equal(result, false);
  });

  it('rejects a request with an incorrect signature', () => {
    const verify = createTwilioRequestVerifier({ authToken, webhookBaseUrl });

    const result = verify({ req: fakeRequest({ signature: 'not-a-real-signature' }), params: { Body: 'hello' } });

    assert.equal(result, false);
  });

  it('rejects a request with no X-Twilio-Signature header at all', () => {
    const verify = createTwilioRequestVerifier({ authToken, webhookBaseUrl });

    const result = verify({ req: fakeRequest({ signature: undefined }), params: { Body: 'hello' } });

    assert.equal(result, false);
  });
});
